### ISSUE TITLE
Critical: PHP Fatal error During Checkout

### ISSUE THREAD

**Issue by sprankhub** [wirecard/magento-wcp#11]
I get the following error during the checkout process:

    [Thu Jan 12 10:38:09.344543 2017] [:error] [pid 30064] [client 78.94.90.38:39530] PHP Fatal error:  Class 'GuzzleHttp\\Client' not found in /srv/www/htdocs/www.page.com/htdocs/app/code/local/Wirecard/CheckoutPage/Stdlib/Client/ClientAbstract.php on line 263, referer: https://www.page.com/de/checkout/onepage/

**Comment by jakubpolomsky** [comment]
Hi,

I would need some guide how to reproduce these errors. This error does not appear in my logs. My testing environment (as in your shop) 1.9.1.1, php 5.6 and 4.1.1 WCS alongside with 4.1.0 WCP Plugins. As I can see you are probably testing locally. Please bear in mind that our servers cannot reach your server when it's hidden behind a firewall. Your shop needs to be accessible from web in order to complete the transactions.

**Comment by sprankhub** [comment]
Magento 1.7.0.2, PHP 5.5, latest WCP extension. If you search for `GuzzleHttp` in this repository, it is totally clear that this error appears. In `WirecardCEE_Stdlib_Client_ClientAbstract`, you use `GuzzleHttp`, but you do not include it anywhere.

I am not testing locally, this was live. The error occurred as soon as I clicked on "buy now".

**Comment by jakubpolomsky** [comment]
Magento 1.7.0.2 is not supported as it does not contain multiple libraries required by us. Try upgrading to 1.9.x.x

**Comment by sprankhub** [comment]
We upgraded to 1.9.3.1 and still get the same error after clicking on "buy now"! This error totally makes sense:

> If you search for GuzzleHttp in this repository, it is totally clear that this error appears. In WirecardCEE_Stdlib_Client_ClientAbstract, you use GuzzleHttp, but you do not include it anywhere.

Please fix this issue ASAP!

**Comment by sprankhub** [comment]
Any news?

**Comment by jakubpolomsky** [comment]
This issue will be resolved tomorrow. The fix would be to use older version of the client library which didn't use guzzle but zend (which is a part of the magento) So if you need to fix your shop asap then copy the `/app/code/local/Wirecard/CheckoutSeamless/Stdlib` and paste it into `/app/code/local/Wirecard/CheckoutPage/Stdlib` overwriting the files. This will be pushed soon and if you are watching this thread, you will get notified.
