### ISSUE TITLE
SSL Verificiation

### ISSUE THREAD

**Issue by andrewhowdencom** [wirecard/magento-wcp#13]
Am I to understand correctly that, given this comment;

https://github.com/wirecard/magento-wcp/blob/0b7dafb12c146db237f13cc1975449fa9533735d/app/code/local/Wirecard/CheckoutPage/Stdlib/Client/ClientAbstract.php#L433

SSL certificates are not verified?

**Comment by andrewhowdencom** [comment]
With further inspection, it appears that PHP uses peer verification by default for the stream_socket_layer stuff.

**Comment by jakubpolomsky** [comment]
You are  correct. These lines are for debugging or  testing purposes only. If you don't have any certificate, this would be the place to tell the app "you HAVE" one. Thank you for asking
