### ISSUE TITLE
modman file broken

### ISSUE THREAD

**Issue by mmodler** [wirecard/magento-wcp#15]
Hi wirecard extension team,

(at least) in release 2.4 the modman file is broken:

WARNING: Target does not exist
 app/code/local/Wirecard/WirecardCEE app/code/local/Wirecard/WirecardCEE

The line should be instead:
app/code/local/WirecardCEE app/code/local/WirecardCEE

**Comment by jakubpolomsky** [comment]
Hi! The updated modman file was pushed, please let us know if it worked for you.
