### ISSUE TITLE
Cannot unset $this

### ISSUE THREAD

**Issue by tismael** [wirecard/magento-wcp#16]
Hi wirecard team,

after upgrading the module to 0462dfed5833f2127a5e8112af32c9a32324d3f8 (4.2.0 with fix for #15) I am now getting the following error:
PHP Fatal error:  Cannot unset $this in
app/code/local/WirecardCEE/Stdlib/Client/ClientAbstract.php on line 300

After doing some research I found out that calling unset($this) seems to be depracated. 
See https://bugs.php.net/bug.php?id=36971

**Comment by rinnhofer** [comment]
Hello,

we have recently discovered the issue with the unset call in our client library and fixed it, you can find a working version here https://github.com/wirecard/checkout-client-library/tree/3.3.5
We will update the plugin according to the issue as soon as possible.

Kind regards
