### ISSUE TITLE
Division by zero when shipping amount of order is 0

### ISSUE THREAD

**Issue by darinda** [wirecard/magento-wcp#24]
payment will fail if shipping amount for the order is zero due to a division by zero when calculating tax rate in the following file:

https://github.com/wirecard/magento-wcp/blob/f5c4e4db3ec53bc2dd4433f4225d4ebbf0dab5a3/app/code/community/Wirecard/CheckoutPage/Model/Abstract.php#L195

`$bitem->getUnitNetAmount()` equals `$order->getShippingAmount()` (L193) which can be zero resulting in an exception

**Comment by jakubpolomsky** [comment]
You are correct. We will fix this in the next release. Thank you for your input

**Comment by jakubpolomsky** [comment]
This issue was fixed. Thank you for waiting.
