### ISSUE TITLE
no payment method on checkout with recurring profiles

### ISSUE THREAD

**Issue by roman204** [wirecard/magento-wcp#5]
When a customer want to checkout no payment methods are available from this module.
No class from this module implements Mage_Payment_Model_Recurring_Profile_MethodInterface? 
In Readme notice the last point is 
- Support of recurring payments (subscriptions, one-click checkout).

How to get payment methods from wirecard working with recurring Profiles?

**Comment by christianfessl** [comment]
Hi

thank you very much for your input, we will put this topic on our roadmap, unfortunately I cannot tell you a release date when this will be implemented on our side.

If you need detailed information regarding the implementation of recurring payments via WCP you can find them in our Online Guides: 
* https://guides.wirecard.at/back-end_operations:transaction-based:recurpayment
and
* https://guides.wirecard.at/back-end_operations:transaction-based:table

best regards
Christian
