### ISSUE TITLE
Fatal Error when saving Order from Script

### ISSUE THREAD

**Issue by tstrohmeier** [wirecard/magento-wcp#8]
When a class of Wirecard_Checkoutpage_Model_* is called you get following Exception:

`Fatal error: Class 'WirecardCEE_QPay_PaymentType' not found in /path/app/code/core/Mage/Core/Model/Config.php on line 1354`

This is the case if you try to update a order. In the save method Magento tries to save Wirecard_Checkoutpage_Model_* before the order and the script crashes with an fatal error.
The fatal error is caused by the reason that `class_exists($className)` returns true but `$obj = new $className($constructArguments);` is not able to find that class.

In front end this is no problem because in the event 'controller_front_init_before' the Observer Wirecard_CheckoutPage_Model_Autoloader->addAutoloader()  is called which is adding the autoloader. 

The _solution_ we found is:

`$autoloader = Mage::getModel('Wirecard_CheckoutPage_Model_Autoloader');
 spl_autoload_register(array($autoloader, 'autoload'), true, true);`

**Comment by jakubpolomsky** [comment]
Hello,

thank you for your input. There would be another option to solve this too. Another event can be used to register the autoloader. There's a nice list of all of them [here](https://magento2.atlassian.net/wiki/display/m1wiki/Magento+1.x+Events+Reference) 

I'd like to add this to our next release, but I need more informations from you. How do you edit the order? Where do you call the update method? Doing these edits from backend doesn't produce any errors.

Could you please provide some steps to reproduce?

Thank you

**Comment by tstrohmeier** [comment]
Thanks for your quick reply. I'm working with a script which is called per cmd line. 
You can reproduce with the following script:


    require_once "app/Mage.php";

    Mage::app();

    // Without this block the script fails with a fatal error
    $autoloader = Mage::getModel("Wirecard_CheckoutPage_Model_Autoloader");
    spl_autoload_register(array($autoloader, "autoload"), true, true);


    $processing_orders = Mage::getModel("sales/order")->getCollection()
        ->addFieldToFilter("status","'processing");

    foreach ($processing_orders as $order) {
        echo "ORDER id " . $order->getId() . " #" . $order->getIncrementId()."\n";

        // If order is exported then set status pending_shipment
        $order->setState("complete", true);
        $order->setStatus("complete", true);
        $order->save(); // Without the added autoloader this call fails
    }

**Comment by jakubpolomsky** [comment]
Hi!

the workaround you proposed will be the only solution for now. It will be noted in the online guides and later on, with some major update, we'll try to separate the payment class from the plugin, so that no autoloading is needed. Thank you for your patience and time.

Kind regards
